appointments/urls.py
from django.urls import path

from . import views

app_name = 'appointments'
urlpatterns = [
    path('', views.index, name='app_index'),
    path('add', views.add, name='app_add'),
    path('list', views.getAppointments, name='app_list'),
]

demo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('appointments.urls')),
    # path('admin/', admin.site.urls),
]

appointments/models.py
from django.utils import timezone
from django.db import models


class Appointment(models.Model):
    app_date = models.DateTimeField('Appointment date', null=True)
    description = models.CharField(max_length=200)

    def __str__(self):
        return self.description

    def is_upcoming(self):
        return self.app_date >= timezone.now()

appointments/forms.py
import datetime

from django import forms

from .models import Appointment


class AppointmentForm(forms.ModelForm):
    date = forms.DateField(help_text="MM/DD/YYYY")
    time = forms.TimeField(help_text="HH:MM")

    def __init__(self, *args, **kwargs):
        super(AppointmentForm, self).__init__(*args, **kwargs)
        self.fields['date'].widget.attrs['class'] = 'form-control form-control-sm'
        self.fields['time'].widget.attrs['class'] = 'form-control form-control-sm'
        self.fields['description'].widget.attrs['class'] = 'form-control form-control-sm'

    def save(self, commit=True):
        instance = super(AppointmentForm, self).save(commit=False)
        
        if commit:
            if self.cleaned_data.get('date') and self.cleaned_data.get('time'):
                instance.app_date = \
                    datetime.datetime.combine(self.cleaned_data.get('date'), 
                                              self.cleaned_data.get('time'))
            instance.save()
        return instance

    class Meta:
        model = Appointment
        fields = ['date', 'time', 'description']
        help_texts = {
            'description': 'Appointment description',
        }

appointments/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import HttpResponseRedirect, JsonResponse

from .models import Appointment
from .forms import AppointmentForm


def index(request):
    form = AppointmentForm()

    context = {
        'form': form, 
        'hide_form': True
    }
    return render(request, 'appointments/index.html', context)


def getAppointments(request):
    keyword = request.POST.get('keyword', '').strip()
    select_data = {"date": """strftime('%%m/%%d', app_date)""",
                   "time": """strftime('%%H:%%M', app_date)"""}

    appointment_list = Appointment.objects.extra(select=select_data).order_by('app_date')
    if len(keyword) > 0:
        appointment_list = appointment_list.filter(description__icontains=keyword)

    data = {
        'list': list(appointment_list.values("date", "time", "description"))
    }
    return JsonResponse(data)


def add(request):
    form = AppointmentForm(request.POST)

    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('appointments:app_index'))

    context = {
        'form': form, 
        'hide_form': False
    }
    return render(request, 'appointments/index.html', context)

templates/appointments/index.html
{% extends 'master.html' %}
{% load static %}

{% block header %}
<link rel="stylesheet" type="text/css" href="{% static 'appointments/style.css' %}" />
<script src="{% static 'appointments/appointment.js' %}"></script>
{% endblock header %}



{% block content %}
<div class="row top-buffer ">
<div class="col-sm-12">
    <input type="button" value="New" id="btn_new" class="btn btn-primary btn-sm" style="{% if not hide_form %}display:none{% endif %}"/>

    <form action="{% url 'appointments:app_add' %}" method="post" 
        onsubmit="this.disabled=true" 
        id="form_add" style="{% if hide_form %}display:none{% endif %}">
        {% csrf_token %}

        <input type="submit" value="Add" id="btn_add" class="btn btn-success btn-sm"/>
        <input type="button" value="Cancel" id="btn_cancel"  class="btn btn-secondary btn-sm"/>
        <div class="clearfix"></div>

        {% if form.non_field_errors %}
        <div class="invalid-feedback" style="display:block">{{form.non_field_errors}}</div>
        {% endif %}

        {% for field in form %}
        <div class="form-group row">
            <label for="{{field.id_for_label}}" class="col-sm-2 col-form-label">{{field.label}}</label>
            <div class="col-sm-4">{{field}}</div>
            <small id="passwordHelpInline" class="text-muted">
                {{field.help_text}}
            </small>
            {% if field.errors %}
            <div class="invalid-feedback col-sm-4" style="display:block">{{field.errors}}</div>
            {% endif %}
        </div>
        {% endfor %}
    </form>
</div>
</div>


<div class="row top-buffer">
    <div class="col">
        <input type="input" id="txt_keyword" value="" class="form-control form-control-sm"/>
    </div>
    <div class="col">
        <input type="button" value="Search" id="btn_search" class="btn btn-secondary btn-sm"/>
    </div>
    {% csrf_token %}
</div>

<div class="row">
<div class="col-sm-8">
    <table id="tbl_app" class="table table-sm table-striped table-hover">
        <thead class="thead-dark">
            <tr>
                <th>Date</th>
                <th>Time</th>
                <th>Description</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td colspan="3">No appointments are available.</td>
            </tr>
        </tbody>
    </table>
</div>
<div class="col-sm-4"></div>
</div>

{% endblock content %}

templates/master.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Demo</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    {% block header %}
    {% endblock header %}
</head>

<body>
    <div class="container">
    {% block content %}
    {% endblock content %}
    </div>
</body>
</html>